# Generated by Django 4.0.3 on 2022-03-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('difficulty', models.SmallIntegerField()),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject', to='thanatos_site.subject')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type', to='thanatos_site.type')),
            ],
        ),
    ]
