# Generated by Django 4.0.3 on 2022-03-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thanatos_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('difficulty', models.SmallIntegerField()),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject', to='thanatos_site.subject')),
            ],
        ),
    ]
