# Generated by Django 4.0.3 on 2022-05-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanatos_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='options',
            field=models.TextField(default=None),
        ),
    ]
